- package-lock.json
- plugins/plotly-express/src/js/package.json
- plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
- plugins/plotly-express/src/js/src/PlotlyExpressChartPanel.tsx
- plugins/plotly-express/src/js/src/PlotlyExpressChartUtils.ts
> fix: 3d view resetting on tick

- plugins/matplotlib/setup.cfg
- plugins/plotly-express/setup.cfg
- plugins/plotly/setup.cfg
The config file updates were not updated properly during the monorepo transition
> Fixing config files

- plugins/plotly-express/src/deephaven/plot/express/plots/PartitionManager.py
- plugins/plotly-express/src/deephaven/plot/express/plots/_private_utils.py
- plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
- plugins/plotly-express/src/deephaven/plot/express/preprocess/HistPreprocessor.py
- plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariatePreprocessor.py
- plugins/plotly-express/test/deephaven/plot/express/plots/test_distribution.py
- plugins/plotly-express/test/deephaven/plot/express/plots/test_scatter.py
Histograms were not rendering properly
Tested with the following
```
from deephaven.plot import express as dx
stocks = dx.data.stocks()
h = dx.histogram(stocks, y="size")
```
> fix: histograms not rendering properly

- README.md
Fixed port number in README
#1504
> fix: Fixed port number in README

- README.md
- package.json
Updated start script to include serving the plugins folder locally.
resolves #152
> feat: Serve plugins with start script

- package-lock.json
> fix: Fixed package lock version

- plugins/ui/src/js/src/layout/ParentItemContext.ts
> fix(ui): Default placement of newly opened components is inconsistent

- package-lock.json
- This does not address #259, just fixing it in the immediate term
> build: Update the package-lock.json

- plugins/example-theme/src/js/package.json
Tested via reproduction steps on the issue
fixes #279
> fix: Added main to example plugin (#279)

- plugins/example-theme/src/js/package.json
Configured example-theme for deployment
resolves #286
> build: Configured example-theme for deployment

- package-lock.json
- Never updated package-lock.json in #287 after changing package.json
- Ran `npm install` and committed the package-lock.json
- #310 created to make CI tests check this when package.json changes
> build: Fix package-lock for example-theme

- plugins/example-theme/src/js/README.md
Very minor wording changes on the two places I got a little stuck.
> docs: update README.md

- plugins/ui/src/deephaven/ui/components/__init__.py
Added missing imports from the ui components
> fix: added missing picker imports

- .github/workflows/modified-plugin.yml
- .github/workflows/release-python-package.yml
- plugins/packaging/.gitignore
- plugins/packaging/LICENSE
- plugins/packaging/README.md
- plugins/packaging/pyproject.toml
- plugins/packaging/setup.cfg
- plugins/packaging/src/deephaven/plugin/packaging/__init__.py
- plugins/packaging/src/deephaven/plugin/packaging/utils.py
- plugins/utilities/.gitignore
- plugins/utilities/LICENSE
- plugins/utilities/README.md
- plugins/utilities/pyproject.toml
- plugins/utilities/setup.cfg
- plugins/utilities/src/deephaven/plugin/utilities/__init__.py
- plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
- plugins/utilities/src/deephaven/plugin/utilities/utils.py
- tools/update_version.sh
Adds new utilities and packaging packages. These can be used for cross-plugin functionality. The first versions have functions that make it simpler to register js plugins.
Part of the work for #316 and #194 
After this is merged I will upload the initial versions to pypi, then use that for the follow-up PR to fix the issues themselves.
> feat: Add utilities package

- plugins/ui/src/deephaven/ui/components/spectrum/toggle_button.py
- toggle_button still wasn't working
- Fixes #420
> fix: toggle_button was not passing through `on_change`

- templates/widget/{{ cookiecutter.python_project_name }}/src/js/src/{{ cookiecutter.__js_plugin_view_obj }}.tsx
Changes widget UI to use deephaven components
> feat: Better ui for widget template

- package-lock.json
- I somehow missed some in my last update #472
> build: Run `npm install` to update package-lock.json

- plugins/ui/src/deephaven/ui/components/spectrum/__init__.py
- plugins/ui/src/deephaven/ui/components/spectrum/basic.py
- plugins/ui/src/deephaven/ui/components/spectrum/contextual_help.py
- plugins/ui/src/deephaven/ui/components/spectrum/layout.py
- plugins/ui/src/deephaven/ui/components/spectrum/validate.py
Closes https://github.com/deephaven/deephaven-plugins/issues/473
**Changes Implemented:**
- Add documentation for contextual_help Adobe Spectrum element
> docs: contextual_help

- plugins/ui/src/deephaven/ui/components/list_action_group.py
- plugins/ui/src/deephaven/ui/components/list_action_menu.py
- plugins/ui/src/js/src/elements/useListViewProps.ts
Resolves: https://github.com/deephaven/deephaven-plugins/issues/484
Changes Implemented: 
- Added docs for list_action_menu_component
> docs: list_action_menu

- plugins/ui/src/deephaven/ui/components/spectrum/__init__.py
- plugins/ui/src/deephaven/ui/components/spectrum/basic.py
- plugins/ui/src/deephaven/ui/components/spectrum/number_field.py
- plugins/ui/src/deephaven/ui/components/spectrum/text_field.py
> docs: number field

- templates/widget/{{ cookiecutter.python_project_name }}/src/js/package.json
- JS was 0.1.0 and Python was 0.0.1, make JS 0.0.1 to match Python version
> fix: Match the JS version number with the Python version in template

- plugins/ui/src/deephaven/ui/components/table.py
- plugins/ui/src/deephaven/ui/elements/UITable.py
- plugins/ui/src/js/src/elements/UITableMouseHandler.ts
- Only the visible row data is passed back
> fix: Don't send back undefined cell data

- plugins/ui/DESIGN.md
Resolves https://github.com/deephaven/deephaven-plugins/issues/191
**Changes Implemented:** 
- Outlines design for refactored ui.tabs component in DESIGN.md with examples
_Discussion threads that shaped design are in PR that will handle implementation_: https://github.com/deephaven/deephaven-plugins/pull/489
> refactor: Refactored ui.tabs component design

- .github/workflows/modified-plugin.yml
- Previously was only running on main
> ci: Test modified plugins in the release branches

- .github/workflows/modified-plugin.yml
- Cherry-pick of #556 
- Previously was only running on main
> ci: Test modified plugins in the release branches (#556)

- plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
Add datasets for funnel, funnel_area, and timeline plot types
> feat: add dx.data.jobs and dx.data.marketing example data sets

- plugins/ui/src/deephaven/ui/components/icon.py
- plugins/ui/src/deephaven/ui/components/types/layout.py
> docs: icon

- plugins/ui/src/js/src/elements/UITable.tsx
- plugins/ui/src/js/src/elements/utils/UITableMouseHandler.ts
Fixes #529 
Based on refactor PR which drops the index from the callback #592. Need to rebase and drop the 1st 2 commits after that merges
> fix: ui.table cell and row press event data can be wrong

- plugins/plotly-express/src/deephaven/plot/express/data/__init__.py
Unfortunately, I forgot this important step.
> fix: add datasets to import to actually use them

- plugins/ui/src/deephaven/ui/components/__init__.py
- plugins/ui/src/deephaven/ui/components/basic.py
- tests/app.d/ui_render_all.py
Component was never implemented and is now unecessary.
> feat: delete unused ui.icon_wrapper

- plugins/ui/docs/components/button.md
First draft of a complete component documentation for ui.button.
> docs: ui.button doc page

- plugins/ui/src/deephaven/ui/components/__init__.py
- plugins/ui/src/deephaven/ui/components/basic.py
- plugins/ui/src/deephaven/ui/components/tab_panels.py
> docs: tab_panels

- .github/workflows/publish-alpha.yml
- .github/workflows/publish-packages.yml
- .npmrc
- Maybe this will fix why it's not currently publishing
- Maybe fixes #617
> ci: Add provenance to publish JS actions

- plugins/ui/src/deephaven/ui/components/__init__.py
- plugins/ui/src/deephaven/ui/components/basic.py
- plugins/ui/src/deephaven/ui/components/switch.py
- plugins/ui/src/deephaven/ui/components/text.py
> docs: switch and text

- plugins/ui/src/js/src/errors/NestedPanelError.ts
- plugins/ui/src/js/src/errors/index.ts
- plugins/ui/src/js/src/layout/ReactPanel.tsx
> fix: invalid ui.panel usage should result in clear error

- plugins/plotly-express/docs/README.md
- plugins/plotly-express/docs/sidebar.json
- plugins/plotly-express/docs/sub-plots.md
- plugins/ui/docs/Plotting.md
- plugins/ui/docs/README.md
- plugins/ui/docs/sidebar.json
Create sidebar.json file and adjust readme intro for dh.ui docs
> docs: add sidebar to UI docs and adjust readme

- .github/workflows/make-docs.yml
- .github/workflows/modified-plugin.yml
Sphinx_ext was missing in ui and the requirements file was moved
> fix: Add sphinx_ext to ui

- package-lock.json
> refactor: Update package-lock.json for plotly removal

- plugins/plotly-express/docs/README.md
- plugins/plotly-express/docs/density_heatmap.md
- plugins/plotly-express/docs/scatter.md
Fixes #608 
#598 should be merged first
Adds some initial density heatmap docs
> docs: Add initial density heatmap docs

- plugins/plotly-express/docs/README.md
I looked over the additions I made to the readme, and noticed some small problems. This fixes them.
> docs: small changes to plotly-express readme

- plugins/ui/docs/components/button.md
- plugins/ui/docs/hooks/use_state.md
- plugins/ui/docs/sidebar.json
- First hook to be documented
- Added usage, API reference, and details of the hook
> docs: Add docs for use_state hook

- templates/widget/{{ cookiecutter.python_project_name }}/setup.cfg
- templates/widget/{{ cookiecutter.python_project_name }}/src/js/package.json
- templates/widget/{{ cookiecutter.python_project_name }}/src/js/src/{{ cookiecutter.__js_plugin_view_obj }}.tsx
- Update required web packages to 0.85.x and jsapi-types
- Use the correct types in JS, clean up warnings
> fix: Template errors in JS

- plugins/ui/docs/sidebar.json
I guess I'll probably want some sort of validation job eventually for this
> docs: fix use_state sidebar docs links

- plugins/ui/docs/components/text_area.md
Closes #678
Assuming the changes proposed in #652
> docs: ui.text_area

- docker-compose.yml
> build: Removed deprecated version attribute

- plugins/ui/docs/components/view.md
> docs: ui.view

- plugins/ui/src/deephaven/ui/components/checkbox.py
- plugins/ui/src/deephaven/ui/components/content.py
- plugins/ui/src/deephaven/ui/components/flex.py
- plugins/ui/src/deephaven/ui/components/form.py
- plugins/ui/src/deephaven/ui/components/fragment.py
- plugins/ui/src/deephaven/ui/components/grid.py
- plugins/ui/src/deephaven/ui/components/heading.py
- plugins/ui/src/deephaven/ui/components/panel.py
- plugins/ui/src/deephaven/ui/components/picker.py
- plugins/ui/src/deephaven/ui/components/row.py
- plugins/ui/src/deephaven/ui/components/stack.py
- plugins/ui/src/deephaven/ui/components/text.py
- plugins/ui/src/deephaven/ui/components/view.py
> fix: autodoc failures hotfix

- plugins/ui/docs/components/range_slider.md
- plugins/ui/docs/components/text_area.md
- plugins/ui/src/deephaven/ui/components/range_slider.py
> docs: ui.range_slider

- sphinx_ext/deephaven_autodoc.py
Fixes #795
Fixed issue where a function with a single parameter wasn't provided as a list, so it wasn't processed correctly.
Also took the opportunity to add better errors to this script to point out the issue that needs to be fixed as granularly as possible.
> fix: Autodoc function parameters not rendering as list when only a single arg

- plugins/ui/docs/hooks/use_effect.md
- plugins/ui/docs/sidebar.json
- Give some examples of connecting to a server using requests and multi-threading
- Have an example of creating a custom hook
- Specify what the different dependency list options are
- Fixes #727
> docs: Add use_effect docs

- plugins/ui/src/deephaven/ui/components/table.py
- plugins/ui/src/js/src/elements/UITable/UITable.tsx
- plugins/ui/src/js/src/elements/UITable/UITableUtils.tsx
Closes https://github.com/deephaven/web-client-ui/issues/2129 (May have to move this ticket to plugins repo)
Assumes changes to be made in https://github.com/deephaven/web-client-ui/pull/2183
> feat: expose rollup group behaviour as dh.ui option for UI Table

- package-lock.json
- package.json
- plugins/auth-keycloak/src/js/package.json
- plugins/dashboard-object-viewer/src/js/package.json
- plugins/example-theme/src/js/package.json
- plugins/matplotlib/src/js/package.json
- plugins/plotly-express/src/js/package.json
- plugins/table-example/src/js/package.json
- plugins/ui/src/js/package.json
Upgrades and centralizes the Vite version since we want to use the same version across all plugins
> build: Upgrade to Vite 5

- tests/ui.spec.ts
- Fixes #900 
- Add missing `await`s
> test: fix flaky key tests

- plugins/ui/src/deephaven/ui/components/flex.py
Closes #824 
Separated from markdown docs in other flex [PR](https://github.com/deephaven/deephaven-plugins/pull/785)
> docs: flex pydocs

- plugins/ui/src/js/src/styles.scss
Remove some accidental TODO comments that slipped in with a previous review
> chore: remove errant comments

- plugins/ui/docs/components/text.md
- plugins/ui/docs/sidebar.json
- plugins/ui/src/deephaven/ui/components/text.py
Closes #835
**Additional Info:**
- Link to markdown once implementation is finished
> docs: ui.text

- plugins/ui/docs/components/table.md
- plugins/ui/src/deephaven/ui/components/table.py
- plugins/ui/src/js/src/elements/UITable/UITable.tsx
- plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.test.ts
- plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.ts
- plugins/ui/src/js/src/elements/UITable/UITableMouseHandler.ts
- plugins/ui/src/js/src/elements/UITable/UITableUtils.tsx
- plugins/ui/test/deephaven/ui/test_ui_table.py
Fixes #513
Tested with the snippet I added to the docs for `on_row_press`. Also tested by using a context menu.
> feat: ui.table always_fetch_columns

- plugins/ui/docs/components/toggle_button.md
- plugins/ui/docs/sidebar.json
- plugins/ui/src/deephaven/ui/components/toggle_button.py
> docs: ui.toggle_button

- plugins/ui/docs/components/tabs.md
- plugins/ui/docs/sidebar.json
- plugins/ui/src/deephaven/ui/components/tabs.py
> docs: ui.tabs

- plugins/ui/docs/components/form.md
- plugins/ui/src/deephaven/ui/components/form.py
> docs: form

- plugins/ui/docs/components/list_view.md
DOC-223: ui.list_view selection_mode
> docs: ui.list_view selection_mode

- plugins/ui/src/deephaven/ui/components/basic.py
- plugins/ui/src/deephaven/ui/components/button_group.py
- plugins/ui/src/deephaven/ui/components/content.py
- plugins/ui/src/deephaven/ui/components/dialog.py
- plugins/ui/src/deephaven/ui/components/divider.py
- plugins/ui/src/deephaven/ui/components/footer.py
- plugins/ui/src/deephaven/ui/components/heading.py
https://deephaven.atlassian.net/browse/DH-18398
Checks if a dialog child is valid based on element name.
> fix: ui.dialog should throw error for invalid children

- plugins/ui/docs/components/dashboard.md
- plugins/ui/docs/components/panel.md
- plugins/ui/docs/describing/ui_with_tables.md
- plugins/ui/docs/installation.md
- plugins/ui/docs/sidebar.json
- plugins/ui/docs/tutorial.md
Checked these with the new salmon link checker. After that is merged to salmon, I will add a job for salmon validation.
> docs: Fixing docs links

- plugins/plotly-express/docs/icicle.md
- plugins/plotly-express/docs/sunburst.md
- plugins/plotly-express/docs/treemap.md
Adds information about branchvalues for [DH-18516](https://deephaven.atlassian.net/browse/DH-18516)
[DH-18516]: https://deephaven.atlassian.net/browse/DH-18516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DH-18516: Add branchvalues info to hierarchical plots

- plugins/ui/src/js/src/widget/WidgetHandler.tsx
- Dashboards were breaking on query restart because we tried to reload the dashboard with panels already in the layout
- On a query restart when the dashboard comes back up, remove all existing children from the layout root
- Tested against dev-grizzly2
> fix: DH-19705: Query restart broke ui.dashboards

- plugins/ui/src/js/src/elements/UITable/UITable.tsx
Tested with DH-19973 test plan both on core locally and a core+ PQ on dev-gplus
> fix: DH-19973: Ad-hoc aggregations not persisting on UI Table
