package-lock.json
plugins/plotly-express/src/js/package.json

Need to publish a new version for the plotly express snapshots in docs. I'm pretty sure the current workflow is manually bump the version in the package.json and then run a publish action manually

Bump plotly express JS plugin version

---

plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py

I don't want ticking=false in the example docs, so for them to show something the data set should start with some data already showing, like stocks does.

fix: iris data should start with some data already ticked so docs don't show nothing

---

plugins/plotly-express/src/js/package.json

The web plugin packager script pulls the main field to put in the manifest. This corrects it to point to the bundled file and also bumps the version so a fixed version can be published.

fix: Plotly express package.json main field

---

plugins/matplotlib/src/deephaven/plugin/matplotlib/figure_type.py

- The input table we were using was being created and wasn't being preserved in any liveness scope
- We should eventually move to bidirectional plugin communication instead of using input tables

fix: Error exporting same matplotlib figure twice

---

plugins/plotly-express/src/deephaven/plot/express/__init__.py

Version bump dx to 0.1.0
@mofojed @devinrsmith Are the tokens set properly? I don't think we've pushed a version in this repo yet

build: Version bump dx to 0.1.0

---

.github/workflows/release-python-package.yml

The repository-url is not necessary for publication (see https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) but was necessary for testing. Removing as it is causing an error.

ci: Removing repository-url

---

plugins/ui/DESIGN.md

- Includes a whole bunch of method specifications and deprecations
- Closes #78

docs: Add the `ui.table` spec

---

plugins/plotly-express/src/deephaven/plot/express/__init__.py
plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/generate.py
plugins/plotly-express/src/deephaven/plot/express/plots/__init__.py
plugins/plotly-express/src/deephaven/plot/express/plots/maps.py
plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
plugins/plotly-express/src/js/src/PlotlyExpressChartPanel.tsx
plugins/plotly-express/test/deephaven/plot/express/plots/test_maps.py

Closes #29, closes #28, closes #27, closes #26, and closes #21
Adds basic capabilities for all maps with the exception of choropleth
I originally was trying to include choropleths as well but they're a bit more complicated and I already have spent a bit too long on this for the moment. The other maps are basically free to implement.
There is a graphical issue with density mapbox that would be good for @mattrunyon to look at when adding the defaults. The data is there but not being drawn.
Here's some code to recreate the issue:
```
from deephaven import time_table
import random 
import pandas as pd
import deephaven.pandas as dhpd
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/earthquakes-23k.csv')
t = dhpd.to_table(df)
fig = …
```

feat: Adding maps

---

package-lock.json
plugins/ui/src/deephaven/ui/__init__.py
plugins/ui/src/deephaven/ui/_internal/utils.py
plugins/ui/src/deephaven/ui/components/__init__.py
plugins/ui/src/deephaven/ui/components/make_component.py
plugins/ui/src/deephaven/ui/components/panel.py
plugins/ui/src/deephaven/ui/components/table.py
plugins/ui/src/deephaven/ui/elements/BaseElement.py
plugins/ui/src/deephaven/ui/elements/Element.py
plugins/ui/src/deephaven/ui/elements/UITable.py
plugins/ui/src/deephaven/ui/elements/__init__.py
plugins/ui/test/deephaven/ui/test_ui_table.py

- Basic ui.table on_row_double_press functionality added
- Does not include the JS side that can handle the ui.table for now

feat: First pass of ui.table functionality

---

plugins/ui/src/deephaven/ui/elements/FunctionElement.py

This will be required for anything that uses a table listener according to Colin. Probably also any 3rd party plugin that consumes a table directly and doesn't manage its liveness. Existing plotting and plotly-express have been modified to be robust about managing the liveness of their tables, but a 3rd party plugin might not be as robust. This should help make things easier for plugin authors
I tested w/ plotly-express locally w/o its liveness scope fix. Also needed plotly-express as a `WidgetPlugin` which I will post a PR for.

feat: Wrap UI components in their own liveness scopes

---

.github/workflows/test-python-package.yml

- The `github.event.inputs` syntax was for `workflow_dispatch.inputs`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
- Correct it to use the syntax for `workflow_call.inputs`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
- Fixes #107

ci: Use `inputs` instead of `github.event.inputs`

---

README.md

The process has changed, no more manifest.json is required

docs: Update readme to use new instructions for loading JS plugins

---

plugins/ui/DESIGN.md

- Also added ui.row, ui.column, ui.stack

docs: Add the ui.dashboard spec

---

plugins/ui/src/deephaven/ui/elements/FunctionElement.py
plugins/ui/src/deephaven/ui/renderer/Renderer.py

Nested components with tables were getting killed if the table was not created in the top-most component

fix(ui): Wrap renderer in liveness scope instead of function element

---

plugins/ui/DESIGN.md

Spec for use_viewport_data, modeled after [setViewport](https://deephaven.io/core/docs/reference/js-api/documentation/#methods-2)
One question - it seems like the best way to achieve the row subsetting is to use the `slice` method. Would it be reasonable to also allow percents like `slice_pct` or perhaps heads or tails of data? maybe different hooks?

docs: use_viewport_data hook spec

---

package-lock.json
plugins/plotly-express/src/js/package.json
plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx
plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
plugins/plotly-express/src/js/src/PlotlyExpressChartPanel.tsx
plugins/plotly-express/src/js/src/PlotlyExpressChartUtils.ts
plugins/plotly-express/src/js/src/PlotlyExpressPlugin.ts
plugins/plotly-express/src/js/src/index.ts
plugins/plotly-express/src/js/src/useHandleSceneTicks.ts

Updates plotly-express to use the latest web-client-ui packages which allow for loading it properly via widget plugins after the ui.panel PR changes

feat: plotly-express Deephaven UI widget loading

---

.github/workflows/modified-plugin.yml

- Checks skipped with the "paths" filter never run, but we want to have branch protection based on the `test-python` and `test-js` steps
- GitHub recommends not filtering on paths for required actions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
- Don't filter on paths for triggering the action; each step is already conditional on if there were actually changes to the package or not

ci: Always run the `modified-plugin` actions, don't use paths filter

---

.github/workflows/modified-plugin.yml

- Should pass if the previous tests pass, otherwise it should fail
- Tested with a whole bunch of actions in my fork: https://github.com/mofojed/deephaven-plugins/pulls
- Tested scenarios where both actions were skipped, both passed, both failed, or just one action failed, and the test-results action was always the correct success/failure state
- Still need to update the infra protection

ci: Add a test-results action that is the result of the previous tests

---

plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/generate.py

- We don't want nulls to be converted in our case
- Breaking change introduced with https://github.com/deephaven/deephaven-core/pull/4815 changed the default backend

fix: Set dtype_backend to None

---

plugins/ui/DESIGN.md

We could use this in the tooltip and in the enterprise new tab screen.

docs: added `description` on ui.dashboard

---

plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py

Better type hinting support means this mistake was now actually triggering an error. 
Engine is currently returning numpy types instead of python types, which is a bug in core. Initial random.seed(seed) is printing this error because of the numpy.int64 type, but is expected to be fixed in the next dhc release.
> DeprecationWarning: Seeding based on hashing is deprecated
since Python 3.9 and will be removed in a subsequent version. The only
supported seed types are: None, int, float, str, bytes, and bytearray.
See: deephaven/deephaven-core#4933

fix: type hint was wrong type in dx data generator

---

plugins/ui/DESIGN.md
plugins/ui/src/deephaven/ui/components/make_component.py
plugins/ui/src/deephaven/ui/elements/Element.py
plugins/ui/src/deephaven/ui/elements/__init__.py
plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
plugins/ui/src/deephaven/ui/renderer/RenderedNode.py
plugins/ui/src/js/src/ObjectView.tsx
plugins/ui/src/js/src/UITable.tsx
plugins/ui/src/js/src/WidgetHandler.tsx
plugins/ui/src/js/src/WidgetTestUtils.ts
plugins/ui/src/js/src/WidgetTypes.ts
plugins/ui/test/deephaven/ui/test_encoder.py

- Instead of resending the full list of exported objects each time, just send the newly exported objects
- Increment the ID for each new object that is created
- Keep a weak reference to old objects so they are released when no longer referenced
- Objects remain the same between renders 
- Tested using the steps in #128 
- Fixes #128, fixes #67
- Needs https://github.com/deephaven/deephaven-core/pull/4909 to handle fetching objects multiple times if necessary
BREAKING CHANGE: JSON protocol now keeps the IDs of objects and callables stable between re-renders, and only exports new objects with each documentUpdated event. The client must track the old objects independently.

feat(ui): Only send new exported objects

---

plugins/ui/src/js/src/DashboardPlugin.tsx

- Needed to listen for the `PanelEvent.CLOSE` event
- Fixes #167

fix: Close panels when object is nulled out

---

docker-compose.yml
package.json

- Noticed since switching to a docker-compose, that changes I made to DEMO.md weren't being copied to the image if I hadn't made any other changes and the image still existed
- Instead of doing a docker-compose down after and removing the image, just add a volume for the data directory as well to always get data instead of using data from a previous container
- Tested by running `npm run docker`, closing, then changing the DEMO.md, running `npm run docker` again, and checking my changes to DEMO.md were displayed
- Also tested with a docker-compose.override.yml with a path to a folder for my own data as detailed in the README, and that worked correctly as well

build: Fix docker script to always update the volumes

---

plugins/plotly-express/test/deephaven/plot/express/preprocess/test_TimePreprocessor.py

Fixed time preprocessor tests that were failing due to more granular engine types

fix: Fixed time preprocessor test

---

plugins/matplotlib/src/deephaven/plugin/matplotlib/__init__.py
plugins/matplotlib/src/deephaven/plugin/matplotlib/figure_type.py

`KeyedArrayBackedMutableTable` was renamed, which was causing this to break. Moved to the python api and also fixed some issues with the execution context
```
from deephaven.plugin.matplotlib import TableAnimation
from deephaven import pandas as dhpd
from deephaven import time_table
import matplotlib.pyplot as plt
import seaborn as sns  
import pandas as pd
tt = time_table("PT1S").update(["X = 0.2 * i", "Y = Math.cos(X)"])
fig, ax = plt.subplots() # Create a new figure
def update_fig(data, update):
ax.clear()
df = dhpd.to_pandas(tt.view(["X", "Y"]))
sns.lineplot(df, x="X", y="Y")
line_plot_ani = TableAnimation(fig, tt, update_fig)
```

fix: Matplotlib input table and execution context not working

---

docker/config/deephaven.prop

- plotly-express JS plugin is included in the docker container, so no need to install it separately

fix: plotly-express error when running from docker

---

plugins/ui/src/js/src/WidgetHandler.tsx

- This is a bigtime pitfall for Enterprise vs. Core plugins. Need to have this as a warning, as it's impossible for Enterprise to get the Community API in time to wrap the dashboard plugins...
- Ticket https://deephaven.atlassian.net/browse/DH-16228 for tracking loading the API better on Enterprise side

fix: Don't use the API in the DashboardPlugin

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
.prettierignore
.prettierrc
README.md
docker/data/storage/layouts/demo-layout.json
package.json
plugins/manifest.json
plugins/matplotlib/README.md
plugins/plotly-express/README.md
plugins/plotly/README.md
plugins/ui/DESIGN.md
plugins/ui/examples/README.md

Support lerna scopes in npm start

feat: Support lerna scopes in npm start

---

package-lock.json
plugins/ui/examples/README.md
plugins/ui/setup.cfg
plugins/ui/src/deephaven/ui/_internal/RenderContext.py
plugins/ui/src/deephaven/ui/_internal/__init__.py
plugins/ui/src/deephaven/ui/_internal/shared.py
plugins/ui/src/deephaven/ui/elements/FunctionElement.py
plugins/ui/src/deephaven/ui/hooks/__init__.py
plugins/ui/src/deephaven/ui/hooks/use_memo.py
plugins/ui/src/deephaven/ui/hooks/use_render_queue.py
plugins/ui/src/deephaven/ui/hooks/use_state.py
plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
plugins/ui/src/deephaven/ui/renderer/Renderer.py
plugins/ui/test/deephaven/ui/test_hooks.py
plugins/ui/test/deephaven/ui/test_render.py
plugins/ui/test/deephaven/ui/test_ui_table.py

- Create a thread and queue for applying state updates
- Now callbacks and state updates are all queued on the same thread
- Cleaned up some typing in the `Renderer` class
- Added a `use_render_queue` hook and example for showing how to queue state updates
- Fixes #116
- Tested using the snippet from #116:
```python
from deephaven.ui import use_state
@ui.component
def foo():
a, set_a = use_state(0)
b, set_b = use_state(0)
print(f"Render with a {a} and b {b}")
def handle_press():
set_a(a + 1)
set_b(b + 1)
return ui.action_button(
f"a is {a} and b is {b}", on_press=handle_press
)
f = foo()
```
- Ensured that the print out was only printed once per press of the button, and both values stayed the same
- Allow a callable to be passed into the use_state setter function …

feat: Queue render state updates on a thread

---

plugins/ui/src/deephaven/ui/hooks/__init__.py
plugins/ui/src/deephaven/ui/hooks/use_execution_context.py
plugins/ui/test/deephaven/ui/test_hooks.py

The hook can be used to call code within an execution context
It is a fairly niche hook, but here as an example of it being used to do a table update on a separate thread
```
import threading
from deephaven.execution_context import get_exec_ctx
from deephaven import agg as agg
import deephaven.pandas as dhpd
stocks = dx.data.stocks()
def print_sym(source):
print(dhpd.to_pandas(source.update(["Symbol = sym"]) \
.agg_by([agg.avg(cols=["AVG = size"])], by=["Symbol"])))
@ui.component
def exec_ctx_hook(source):
with_exec_ctx = ui.use_execution_context()
def thread_func():
#print_sym(source)
with_exec_ctx(lambda: print_sym(source))
def start_thread():
thread = threading.Thread(target=thread_func)
thread.start() …
```

feat: use_execution_context hook

---

plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py

fix: ExecutionContext must be opened before running code on a thread

---

plugins/ui/src/js/src/DashboardPlugin.tsx

This should prevent the whole UI from going blank if there's a rendering error in JS. An example dashboard that would crash the whole UI previously is provided below. Now you get an error message and can still go back to your code studio.
```py
@ui.component
def Foo():
return [
ui.row(ui.stack(ui.panel(ui.text('Foo')))),
ui.row(ui.stack(ui.panel(ui.text('Bar'))))
]
f = ui.dashboard(Foo())
```

feat(ui): Add error boundary to prevent UI crashing due to rendering errors

---

plugins/ui/src/deephaven/ui/hooks/use_state.py

Fixes #237 
@niloc132 raised the point that the `use_state` set functions themselves could possibly handle sending to the render queue
This turns out to be a straightforward change as the context is already in the `use_state` hook and ensures that all `set_*` calls are on the render thread.
The table listener example works with no further changes
```
from deephaven.table import Table
from deephaven import time_table, empty_table, merge
from deephaven import pandas as dhpd
import pandas as pd
def to_table(update):
return dhpd.to_table(pd.DataFrame.from_dict(update))
def add_as_op(ls, t, op):
t = t.update(f"type=`{op}`")
ls.append(t)
@ui.component
def monitor_changed_data(source: Table):
changed, set_changed = ui.use_state(empty_table(0))
show_added, set_show_added …
```

feat: Send all set hooks to render queue

---

plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py

Fixes #227 
Testing with the examples from the issue logged errors, for example:
```
@ui.component
def hi():
something, set_something = ui.use_state(0)
return "Hello, " + something
h = hi()
```
```
Error rendering __main__.hi
Traceback (most recent call last):
File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.8/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 153, in _render
node = self._renderer.render(self._element)
File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.8/site-packages/deephaven/ui/renderer/Renderer.py", line 111, in render
return _render_element(element, self._context)
File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.8/site-packages/deephaven/ui/renderer/R …
```

fix: Better render error handling

---

.gitignore
vite.config.js

Added support for optional `STRICT_PORT` env.
**Testing**
- Create a `.env.development.local` file in the repo root and set `STRICT_PORT=true`
- In another checkout of the plugins repo, run `npm start` (or you could run something else on port 4100)`
- Run `npm start` in repo with the new env file. It should fail due to port already in use
resolves #262

build: Added config for STRICT_PORT

---

.github/workflows/test-js-packages.yml
plugins/ui/src/js/src/ReactPanel.test.tsx

Updated CI caching to use a glob for the `node_modules` directories. The previous wildcard would only search 1 level deep which is not valid for our setup. This should fix some edge cases that could cause test failures if the expected package version was installed to the package's local `node_modules`.
Updated cache action to v4. Added the `save-always` flag to the `node_modules` cache which should work whenever it's fixed. Ticket for the flag not working https://github.com/actions/cache/issues/1315. Without that flag functioning, it acts just like v3 cache

ci: Fix JS caching

---

.gitignore
package-lock.json
plugins/plotly-express/src/js/package.json
plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx
plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
plugins/plotly-express/src/js/src/PlotlyExpressChartPanel.tsx
plugins/plotly-express/src/js/src/PlotlyExpressPlugin.ts
plugins/plotly-express/tox.ini
plugins/ui/src/js/src/DocumentHandler.test.tsx

- DHC version bump
- Fixed infinite loading spinner
fixes #241

fix: Version bump + loading spinner fixes

---

plugins/ui/examples/README.md
plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
plugins/ui/test/deephaven/ui/test_encoder.py

- Referenced a table `t` that did not exist, corrected to reference `formatted_table`
- Needed to refactor how exported objects were being handled - server was just using a WeakKeyDictionary, but the objects were not guaranteed to get cleared out on the server and were being reused between re-renders. The client would always dump old objects after a render, so just always clear out the objects on the server from the previous render. Note that the WeakKeyDictionary is still safe for callables; the client just references them by ID and does not hold a reference to an object, so they can be cleared by the server GC.
- Fixes #265
- Tested using the Stock Rollup example fixed in this PR, it now works correctly.
- Also tested with snippet from #128, ensuring the table still does not flicker.
- …

fix: Stock rollup example was not working

---

plugins/ui/src/deephaven/ui/_internal/__init__.py
plugins/ui/src/deephaven/ui/_internal/utils.py
plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
plugins/ui/test/deephaven/ui/test_utils.py

Fixes #260 
This snippet now works:
```
from deephaven.ui import use_state
@ui.component
def counter():
count, set_count = use_state(0)
return [
ui.action_button(f"Foo {count}", on_press=lambda e: set_count(count + 1)),
ui.action_button(f"Bar {count}", on_press=lambda: set_count(count + 1))
]
c = counter()
```
This implementation is more robust than that though. It supports:
1. Dropping any number of positional args. For example, if the callback supports 3 positional args but only two are defined, the third will be not be passed in.
3. Dropping any unused keyword args. 
4. If `*args` or `**kwargs` are used, all of the relevant args are passed in.

feat: Support for dropping extra callback args

---

plugins/ui/src/js/src/ReactPanel.tsx
plugins/ui/src/js/src/ReactPanelContext.ts
plugins/ui/src/js/src/SpectrumElementUtils.ts
plugins/ui/src/js/src/layout/Column.tsx
plugins/ui/src/js/src/layout/Row.tsx
plugins/ui/src/js/src/spectrum/Flex.tsx
plugins/ui/src/js/src/spectrum/index.ts

Fixes #165 
Some Python that should render the same
```py
from deephaven.ui import use_state
@ui.component
def as_flex():
text, set_text = use_state("hello")
return ui.flex(
ui.flex(
ui.text("Type a message here"),
ui.text_field(value=text, on_change=set_text),
direction="column",
width="50%"
),
ui.text(f"Message received: {text}"),
direction="row"
)
@ui.component
def implicit_panel():
text, set_text = use_state("hello")
return ui.row(
ui.column(
ui.text("Type a message here"),
ui.text_field(value=text, on_change=set_text),
width=50
),
ui.text(f"Message received: {text}")
)
@ui.component
def explicit_panel():
text, set_text = use_state("hello")
return ui.panel(
implicit_panel(),
title="My messaging service"
)
flex = as_flex()
ip = implicit_panel()
ep = …
```

feat: Support column and row within a panel

---

package-lock.json
plugins/plotly-express/src/js/package.json
plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
plugins/plotly-express/src/js/src/PlotlyExpressChartUtils.ts
plugins/plotly-express/src/js/vite.config.ts

Fixes #216 
PlotlyExpressChartModel should just remove the colors on the traces instead of setting them to the UI theme. The UI theme then gets applied via the template colorway

feat: Remove UI theme from PlotlyExpressChartModel

---

plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts

Fixes #179 
Tested by running a server with and without this fix and opening the Memory dev tools tab. Then ran the code in the ticket. The tab without this fix grew steadily in memory consumption over several minutes. The tab with the fix stayed fairly consistent over the same period of time.

fix: Deephaven express memory leak

---

Dockerfile

- Follow up to #285, need to enable the environment variable in the Dockerfile so that the docker container works with Deephaven express

build: Use new environment variable in Dockerfile

---

plugins/ui/test/deephaven/ui/test_hooks.py

Some hook tests rely on table listeners, and they need a bit more time to finish. This currently causes intermittent failures. Bumping from 1 to 2 seconds should be sufficient.

test: Bumping test listener timeout from 1 to 2 seconds

---

plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/test/deephaven/ui/test_hooks.py

Fixes #290
Theoretically, there is some danger in this implementation, as if dependencies change the listener will be called again, but I think it makes more sense than just checking the first time, as the dependencies changing means a completely different call. Maybe we need more danger signs as has been alluded to. Maybe that's a docs issue.

fix: Call listener when do_replay is True for use_table_listener_hook

---

package-lock.json
plugins/ui/src/js/package.json
plugins/ui/src/js/src/elements/UITable.tsx

- Wasn't passing the settings into `IrisGrid`
- Pull the settings from redux and pass them to `IrisGrid`
- Fixes #315
- Verified using the steps in the ticket. The table uses the correct time zone.

fix: Use correct formatting settings for ui.table

---

plugins/ui/DESIGN.md
plugins/ui/src/deephaven/ui/components/picker.py
plugins/ui/src/deephaven/ui/types/types.py

We do not want to support this prop. Removing it.

fix: Remove tooltip prop

---

plugins/plotly-express/src/js/src/DashboardPlugin.tsx
plugins/plotly-express/src/js/src/PlotlyExpressChartUtils.ts
plugins/plotly-express/src/js/src/index.ts

Tested with DHE V+ (1.20231218.176) Core 0.32.1
Closes #308
BREAKING CHANGE:
- `widget` type in the `PanelEvent.OPEN` event arguments has changed from `VariableDefinition` to `VariableDescriptor`

feat: Export plotly-express as a dashboard plugin

---

plugins/example-theme/src/js/package.json

- There is an error thrown when publishing JS packages right now: https://github.com/deephaven/deephaven-plugins/actions/runs/8210757136/job/22458743570
```
lerna WARN Unable to determine published version, assuming "@deephaven/js-plugin-example-theme" unpublished.
Found 2 packages to publish:
- @deephaven/js-plugin-example-theme => 0.1.0
- @deephaven/js-plugin-ui => 0.9.0
lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna ERR! E402 You must sign up for private packages
```
- Make the example package private so it doesn't try to publish it

chore: Make example package private

---

docker/data/storage/notebooks/DEMO.md
plugins/ui/examples/README.md

- Some results were being assigned to a new variable instead of replacing the existing `result` panel
- Add explicit wrapping around text with icon in ui.item case. Created ticket to automatically wrap raw nodes: https://github.com/deephaven/deephaven-plugins/issues/353
- Fix hist_demo. You cannot pass non-hashable objects into a set; in this case we were passing in a dict to the set of dependencies. Need to use an array instead
- Ran through Demo script and made sure there were no errors

docs: Fix the demo script

---

docker/data/storage/notebooks/DEMO.md
plugins/ui/src/deephaven/ui/hooks/use_callback.py
plugins/ui/src/deephaven/ui/hooks/use_effect.py
plugins/ui/src/deephaven/ui/hooks/use_execution_context.py
plugins/ui/src/deephaven/ui/hooks/use_liveness_scope.py
plugins/ui/src/deephaven/ui/hooks/use_memo.py
plugins/ui/src/deephaven/ui/hooks/use_table_data.py
plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/src/deephaven/ui/types/types.py
plugins/ui/test/deephaven/ui/test_hooks.py

Fixes #355 
Only allow tuple and list, and throw if neither.

fix: Tighten use_memo dependency types

---

cog.toml
tools/update_version.sh

- package.json files weren't being included in the commit, just commit everything
- We can assume we're already at a clean slate in the post_package_bump
- Move other JS plugins to use `npm` for the bump

build: Fix build script to commit all files post version bump

---

plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx
plugins/plotly-express/src/js/src/PlotlyExpressChartPanel.tsx

Fixes #377
The issue was the widget changing and thus the model changing, but the `Chart` component was not resetting. `Chart` puts the model layout into its state, so it wasn't updating when the model changed. This could also be fixed in `Chart`, but this is the simplest fix for the dh.ui scenario in the ticket.
This does not fix a scenario where deephaven-express sends a new title (no widget change) as part of an update as `Chart` will still keep its layout over the model's layout in that case. AFAIK there's currently no way to do this though

fix: Deephaven express chart title does not update dynamically

---

package-lock.json
package.json
plugins/ui/src/js/package.json
plugins/ui/src/js/src/DashboardPlugin.tsx
plugins/ui/src/js/src/elements/ElementUtils.test.tsx
plugins/ui/src/js/src/elements/ElementUtils.tsx
plugins/ui/src/js/src/elements/ObjectView.tsx
plugins/ui/src/js/src/elements/SpectrumElementUtils.ts
plugins/ui/src/js/src/elements/SpectrumElementView.tsx
plugins/ui/src/js/src/elements/UITable.tsx
plugins/ui/src/js/src/elements/UITableUtils.tsx
plugins/ui/src/js/src/layout/ReactPanel.tsx
plugins/ui/src/js/src/widget/DashboardWidgetHandler.tsx
plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
plugins/ui/src/js/src/widget/WidgetHandler.tsx
plugins/ui/src/js/src/widget/WidgetTestUtils.ts
plugins/ui/src/js/src/widget/WidgetTypes.ts

chore: Upgraded @deephaven/jsapi-types to 1.0.0-dev0.33.2 (#389)

---

plugins/ui/DESIGN.md
plugins/ui/src/deephaven/ui/components/__init__.py
plugins/ui/src/deephaven/ui/components/list_action_group.py
plugins/ui/src/deephaven/ui/components/list_action_menu.py
plugins/ui/src/deephaven/ui/components/list_view.py
plugins/ui/src/deephaven/ui/components/spectrum/action_button.py
plugins/ui/src/deephaven/ui/types/types.py

fixes #337 
Adds Python list_view implementation

feat: Add Python list_view implementation 

---

plugins/plotly-express/src/deephaven/plot/express/plots/PartitionManager.py
plugins/plotly-express/test/deephaven/plot/express/plots/test_layout.py

Fixes #147 
This was because the title was not being added to the default figure, but it should be as it is assumed to never change.
Tested with the code in the issue as well
```
from deephaven import empty_table, merge, time_table
from deephaven.plot import express as dx
t0 = empty_table(0).update(["x=i", "y=i*Math.random()*i", "z=i%5"])
t1 = empty_table(10).update(["x=i", "y=i*Math.random()*i", "z=i%5"])
t2 = time_table("PT1s").update(["x=i", "y=i*Math.random()*i", "z=i%5"]).drop_columns(["Timestamp"])
t3 = t2.where("x > 1")
p0 = dx.line(t0, x="x", y="y", by=["z"], title="Hello World0")
p1 = dx.line(t1, x="x", y="y", by=["z"], title="Hello World1")
p2 = dx.line(t2, x="x", y="y", by=["z"], title="Hello World2")
p3 = dx.line(t3, x="x", y="y", by=["z"], title="Hello World3")
```

fix: Ensure title is added to default figure

---

cog.toml
tools/update_version.sh

- We only want to bump python packages for that, since it's common to build a wheel and then install it. With JS, the flow isn't like that
- Don't bother bumping the npm package to a dev build

build: Don't bump JS packages for the dev builds

---

plugins/ui/src/js/__mocks__/@deephaven/dashboard.js
plugins/ui/src/js/src/DashboardPlugin.tsx
plugins/ui/src/js/src/layout/ReactPanel.test.tsx
plugins/ui/src/js/src/layout/ReactPanel.tsx
plugins/ui/src/js/src/widget/DocumentHandler.tsx
plugins/ui/src/js/src/widget/WidgetHandler.tsx
plugins/ui/src/js/src/widget/WidgetUtils.test.tsx
plugins/ui/src/js/src/widget/WidgetUtils.tsx

- There was a race condition when replacing the widget, where the old panel content was getting removed before the new panel was being put up
- This was because we were calling `LayoutUtils.openComponent` to open the panel, which would replace the existing panel; which triggered a panel close event, then a panel open event.
- Was also adding panel IDs multiple times to the `panelIds` widget data, which would cause them to re-open even if you "closed" all the panels
- Instead, only call `LayoutUtils.openComponent` if the panel does not yet exist
- If it needs a re-focus in case of metadata change (e.g. re-opening a widget), it will just set it as the active item in the stack, and update the key of the component so that it re-renders clean.
- Add checks to ensure we're not adding `panelIds` …

fix: Re-opening widgets after re-hydrated

---

plugins/ui/DESIGN.md
plugins/ui/src/deephaven/ui/_internal/utils.py
plugins/ui/src/deephaven/ui/components/__init__.py
plugins/ui/src/deephaven/ui/components/date_picker.py
plugins/ui/src/deephaven/ui/components/spectrum/__init__.py
plugins/ui/src/deephaven/ui/components/spectrum/date_picker.py
plugins/ui/src/deephaven/ui/types/types.py
plugins/ui/test/deephaven/ui/test_date_picker.py
plugins/ui/test/deephaven/ui/test_utils.py

fixes #368 
Implements the python side of date picking, including converting all date props to Java date types and wrapping the callback function with the appropriate conversion.

feat: python date picker implementation

---

plugins/ui/src/js/src/elements/spectrum/Button.tsx

resolves #419
Broken by #416, extra prop slipped in while adding types and broke things. Removed the uncessary prop.

fix: buttons not working due to extra prop

---

plugins/ui/src/deephaven/ui/components/spectrum/toggle_button.py

Fixes #420
The code in the issue works now
```
from deephaven.ui import use_memo, use_state
from deephaven import agg
stocks = dx.data.stocks()
def get_by_filter(**byargs):
"""
Gets a by filter where the arguments are all args passed in where the value is true.
e.g.
get_by_filter(sym=True, exchange=False) == ["sym"]
get_by_filter(exchange=False) == []
get_by_filter(sym=True, exchange=True) == ["sym", "exchange"]
"""
return [k for k in byargs if byargs[k]]
@ui.component
def stock_table(source):
is_sym, set_is_sym = ui.use_state(False)
is_exchange, set_is_exchange = ui.use_state(False)
highlight, set_highlight = ui.use_state("")
aggs, set_aggs = ui.use_state(agg.avg(cols=["size", "price", "dollars"]))
by = …
```

fix: add on_change to toggle_button

---

plugins/ui/src/deephaven/ui/hooks/use_table_data.py
plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/test/deephaven/ui/test_hooks.py

fixes #384 
Moves the refreshing table check to ensure the `use_effect` is always called.
Also added a `use_effect` to `use_table_data` to ensure that when a table is swapped it updates the resulting data
Here is an example of flipping between ticking and static tables
```
from deephaven.table import Table
from deephaven import time_table, empty_table
empty_t = empty_table(0)
time_t = time_table("PT1S").tail(1)
@ui.component
def test_component():
empty, set_empty = ui.use_state(True)
val = ui.use_table_data(empty_t if empty else time_t)
button = ui.action_button(str(empty), on_press=lambda: set_empty(not empty))
return [button, str(val)]
data = test_component()
```

fix: Fix conditional use_effect in use_table_listener

---

plugins/ui/src/deephaven/ui/hooks/use_table_data.py
plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/test/deephaven/ui/test_hooks.py

Because the listener function was not memoized in `use_table_data`, the `use_effect` within `use_table_listener` was getting called unnecessarily, which means in some cases table updates can be missed during the start and stop of the listener.
Added fix and caution message in `use_table_listener` for now.
It might be worthwhile making `use_table_listener` more robust in cases where arguments changed, but the table specifically did not. This is not trivial though.

fix: Memoize use_table_data listener

---

plugins/plotly-express/src/deephaven/plot/express/plots/bar.py
plugins/plotly-express/src/deephaven/plot/express/preprocess/TimePreprocessor.py

Tests were failing on #453 due to some parsing issues
This is similar to https://github.com/deephaven/deephaven-core/issues/5373 which I thought was fixed.
Regardless, we shouldn't be using `to_j_instant` in this way due to poor performance. For now I think assuming the column is an `Instant` is fine.

fix: Improve TimePreprocessor code

---

plugins/ui/setup.cfg

- This version of deephaven-plugin-ui is not compatible with older versions of core, as some of the functionality is not in the web UI until 0.34.1
- Bump the minimum install_requires version to 0.34.1 in the setup.cfg

build: Update requirements to require a newer version of core

---

plugins/ui/src/deephaven/ui/hooks/use_cell_data.py
plugins/ui/src/deephaven/ui/hooks/use_column_data.py
plugins/ui/src/deephaven/ui/hooks/use_row_data.py
plugins/ui/src/deephaven/ui/hooks/use_row_list.py
plugins/ui/src/deephaven/ui/hooks/use_table_data.py
plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/test/deephaven/ui/test_hooks.py

Fixes #385 
Table data hooks now allow `None`, and return `None` in that case. Also changed default `sentinel` value to be an empty tuple to ensure there is a difference by default but still falsy.
BREAKING CHANGE: Default sentinel value for table data hooks is now an empty tuple, ()

feat: Table data hooks allow None

---

plugins/matplotlib/README.md
plugins/matplotlib/src/js/package.json

- Fix the repository links in the package.json
- Update casing of matplotlib to Matplotlib in README (that's how it is on the matplotlib site)

docs: Update some information about Matplotlib

---

docker/data/storage/notebooks/DEMO.md

- `marginX` is not a valid prop and was throwing an error
- No need to use it, since the new styling looks good without explicitly setting a margin

docs: Demo used marginX which doesn't exist

---

docker-compose.yml

The root `docker-compose.yml` shouldn't need the `/app.d` mapping any more since the `tests/docker-scripts/docker-compose.yml` one handles tests now.

refactor: Removed /app.d volume from root docker-compose.yml

---

plugins/ui/src/deephaven/ui/hooks/use_callback.py

Fixes #403
I went with Matt's implementation as that seems to mirror React's implementation and it seems to work as intended.
These examples now work
```
from deephaven.ui import use_state
@ui.component
def counter():
count, set_count = use_state(0)
on_press = ui.use_callback(lambda: set_count(lambda c: c + 1), [])
return ui.action_button(
f"You pressed me {count} times", on_press=on_press
)
c = counter()
```
```
from deephaven.ui import use_state
@ui.component
def counter():
count, set_count = use_state(0)
on_press = ui.use_callback(lambda _: set_count(count + 1), [count])
ui.use_effect(lambda: print('Effect'), [on_press])
return ui.action_button(
f"You pressed me {count} times", on_press=on_press
)
c = counter()
```

fix: fix use_callback hook

---

plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
plugins/ui/src/js/src/widget/WidgetHandler.tsx
plugins/ui/src/js/src/widget/WidgetTestUtils.ts

- We were using the same initial data regardless of how long the widget was opened
- We want to keep the same WidgetHandler and panelIds so that panels open in the same spot
- Want to start with a fresh state
- Freeze the initialData whenever the fetched widget is updated
- Fixes #401
- Tested using the steps in the description

fix: Reset state when new instance of widget created

---

plugins/plotly-express/setup.cfg

- Needs the runChartDownsample function exposed, which was pushed with PR https://github.com/deephaven/deephaven-core/pull/5409 and in deephaven-core v0.34.0

build: Require deephaven-core>=0.34.0 for plotly-express

---

plugins/ui/src/js/src/elements/spectrum/TextField.tsx

Resolves https://github.com/deephaven/deephaven-plugins/issues/372
**Changes Implemented:**
- Added a `useEffect` that updates the local `value` state in the `TextField` whenever the `propValue` changes, which is the value that would be changed using the `use_state`

fix: ui.text_field value not changing with use_state

---

plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py

Gets rid of the replayer, which is better for performance.
Also loads the original data for px.data, runs stats on it then uses that for the values of random.gaussian.
Takes about the same amount of time to run as before, but I guess we have less magic values declared, and might be easier to model other generators off of.

refactor: re-write dx.data.iris() using px.data to calculate base mean/std

---

plugins/ui/DESIGN.md

Resolves https://github.com/deephaven/deephaven-plugins/issues/517
**Changes Implemented:**
- Moved position of `ui.item`, `ui.picker`, `ui.list_action_group`, `ui.list_action_menu`, `ui.list_view`, `ui.combo_box` into separate Components section

fix: Clean up positioning and headers of components in DESIGN.md

---

plugins/ui/src/js/src/elements/RadioGroup.tsx
plugins/ui/src/js/src/elements/spectrum/useSelectionProps.ts
plugins/ui/src/js/src/elements/useListViewProps.ts

Most of our dh ui string enumerations are "CAPITALIZED". Make RadioGroup `orientation` prop consistent.
```python
@ui.component
def ui_radio_group():
return ui.radio_group(
ui.radio('One', value="one"),
ui.radio('Two', value="two"),
label="Radio Group",
orientation="HORIZONTAL"
)
my_radio_group = ui_radio_group()
```
#425

feat: Make RadioGroup orientation prop case insensitive

---

plugins/ui/src/js/src/layout/ReactPanel.test.tsx
plugins/ui/src/js/src/layout/ReactPanel.tsx

- Previously, if a child of the ReactPanel threw, it would cause the panel to close, which could cause the widget to close unexpectedly.
- Instead, have the ReactPanel catch the error and display an error view.
- If any of the children of ReactPanel throw, it won't cause the panel to close. It will just show the error in the panel now.
- Tested against Core with a special branch [debug-kill-table](https://github.com/mofojed/web-client-ui/tree/debug-kill-table)
- Run the following snippet to create a panel with a table in it:
```
from deephaven import time_table, ui
p = ui.panel(time_table("PT1s"))
```
- Open the browser console, and enter the command `dhKillTable()`. The table stops ticking as it's closed.
- Hover the mouse over the table. This will trigger a NPE and a debugger …

fix: Wrap the children of ReactPanel with an ErrorBoundary

---

plugins/ui/src/js/src/layout/ReactPanel.test.tsx
plugins/ui/src/js/src/layout/ReactPanel.tsx

- Cherry pick of #565 
- Previously, if a child of the ReactPanel threw, it would cause the panel to close, which could cause the widget to close unexpectedly.
- Instead, have the ReactPanel catch the error and display an error view.
- If any of the children of ReactPanel throw, it won't cause the panel to close. It will just show the error in the panel now.
- Tested against Core with a special branch [debug-kill-table](https://github.com/mofojed/web-client-ui/tree/debug-kill-table)
- Run the following snippet to create a panel with a table in it:
```
from deephaven import time_table, ui
p = ui.panel(time_table("PT1s"))
```
- Open the browser console, and enter the command `dhKillTable()`. The table stops ticking as it's closed.
- Hover the mouse over the table. This will trigger a NPE …

fix: Wrap the children of ReactPanel with an ErrorBoundary (#565)

---

lerna.json
package-lock.json
package.json

- Note there's still some weirdness around how we should handle dist-tags, will address with #557 fixes. This just makes sure I don't publish a version "latest" from this branch
- Update the changelogPreset to use conventionalcommits (was done in web-client-ui with https://github.com/deephaven/web-client-ui/pull/2054)

build: Set distTag to ui-v0.15 for this release branch

---

plugins/ui/setup.cfg

- We need to update the version so that you can install alongside deephaven-core 0.33.5

fix: deephaven-plugin-ui is compatible with deephaven-core 0.33.5

---

plugins/ui/src/js/src/layout/ReactPanel.tsx

- Changing the key whenever the children changed resulted in the key changing every render, which is not what we want
- Don't bother with an error key; when the widget is re-opened, there's already a new key at a higher level so the ErrorBoundary gets reset

fix: Don't use a key for the ErrorBoundary in a Panel

---

plugins/ui/src/js/src/layout/ReactPanel.tsx

- Cherry-pick of #574 
- Changing the key whenever the children changed resulted in the key changing every render, which is not what we want
- Don't bother with an error key; when the widget is re-opened, there's already a new key at a higher level so the ErrorBoundary gets reset

fix: Don't use a key for the ErrorBoundary in a Panel (#574)

---

plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py

The current version of the ticking Gapminder dataset uses a feature only available in Pandas 2.1.4. Deephaven will work with Python 3.8, but Pandas 2.1 has a minimum Python version of 3.9. So, the feature that Gapminder depends on is not guaranteed to be available to DH. This PR removes that feature and replicates the functionality with an older feature.

fix: gapminder to be compatible with Pandas 2.0.3

---

plugins/ui/src/deephaven/ui/components/table.py
plugins/ui/src/deephaven/ui/types/types.py
plugins/ui/src/js/src/elements/UITable.tsx
plugins/ui/src/js/src/elements/utils/UITableMouseHandler.ts
plugins/ui/src/js/src/elements/utils/UITableUtils.tsx

Fixes #528 
BREAKING CHANGE:
`ui.table` row and cell press handlers had their first parameters of row/column index removed. These were an unsafe way to index the table as the index matches the user's view of the table, not the server's view.
For row events, you can add your own key column and use `always_fetch_columns=["my_key_column"]`. This column's data will be included with every row press.
For cell events, switch to a row event with the change above if you need to identify the row of the cell.

refactor: Remove row and column indexes from table press handlers

---

cog.toml
tools/confirm.sh

- Prompt the user with the previous version and the new version when bumping, then ask the user to confirm
- Avoid situations where it bumps to a version we're not expecting

chore: Confirm the user wants to proceed when version bumping

---

plugins/ui/setup.py

- When rebuilding the wheel, it had stale files for the _js files, which was confusing and annoying
- Clean the build directory so it doesn't have stale files
- Still need to run `npm run build` between builds
- Fixes #380

build: Clean the build directory before building the wheel

---

package-lock.json
plugins/ui/src/deephaven/ui/components/table.py
plugins/ui/src/js/package.json
plugins/ui/src/js/src/elements/UITable/UITable.tsx
plugins/ui/src/js/src/elements/UITable/UITableUtils.tsx

Fixes #607
The concern I had about reverse/sort order is that it does matter, but we only apply a post-sort reverse in the UI via the reverse action.
We do however not have that plumbed up properly in IrisGrid (we define pre-sort, but don't use it and don't properly apply the reverse pre-sort if it's specified). But it works for what we want in ui.table
```py
from deephaven.plot import express as dx
_stocks = dx.data.stocks()
stocks_reversed = ui.table(
_stocks,
reverse=True
)
```

feat: Add ui.table reverse prop

---

package-lock.json
plugins/matplotlib/src/js/package.json
plugins/matplotlib/src/js/src/DashboardPlugin.tsx
plugins/matplotlib/src/js/src/MatplotlibPanel.tsx
plugins/matplotlib/src/js/src/MatplotlibPlugin.ts
plugins/matplotlib/src/js/src/MatplotlibView.tsx
plugins/matplotlib/src/js/src/index.ts
plugins/matplotlib/src/js/vite.config.ts

Tested on dev-grizzly w/ a Core+ worker using this snippet. Also imported the all types dashboard from DH-16263 and that loaded on dev-grizzly properly.
```py
import matplotlib.pyplot as plt
mpl_fig = plt.figure()
ax = mpl_fig.subplots()  # Create a figure containing a single axes.
ax.plot([1, 2, 3, 4], [4, 2, 6, 7])  # Plot some data on the axes.
@ui.component
def test():
mpl_fig = plt.figure()
ax = mpl_fig.subplots()  # Create a figure containing a single axes.
ax.plot([1, 2, 3, 4], [4, 2, 6, 7])  # Plot some data on the axes.
return mpl_fig
mpl_dhui = test()
```

fix: DH-17393: Add matplotlib legacy dashboard plugin for DHE

---

package-lock.json
plugins/ui/src/js/src/errors/MixedPanelsError.ts
plugins/ui/src/js/src/errors/NoChildrenError.ts
plugins/ui/src/js/src/widget/DocumentHandler.tsx
plugins/ui/src/js/src/widget/WidgetErrorUtils.test.ts
plugins/ui/src/js/src/widget/WidgetErrorUtils.ts
plugins/ui/src/js/src/widget/WidgetErrorView.tsx
plugins/ui/src/js/src/widget/WidgetUtils.tsx

- We had a circular dependency of ReactPanel => WidgetErrorView => WidgetUtils => ReactPanel, and ReactPanel
- This caused ReactPanel to be `null` in tests when imported in code unexpectedly
- Removed the circular dependency and added some tests to the WidgetErrorView
- Resolve the widgets opened/closed state after the current render has completed, rather than after each close immediately
- Transitioning from an errored out panel state would cause that panel to close, which could be the last panel that was open in the widget and then it'd disappear
- Fixes #510

fix: deephaven.ui panels disappearing in some cases

---

plugins/ui/src/deephaven/ui/components/__init__.py
plugins/ui/src/deephaven/ui/components/text_area.py
plugins/ui/src/deephaven/ui/types/types.py
plugins/ui/src/js/src/elements/TextArea.tsx
plugins/ui/src/js/src/elements/TextField.tsx
plugins/ui/src/js/src/elements/hooks/index.ts
plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
plugins/ui/src/js/src/elements/index.ts
plugins/ui/src/js/src/elements/model/ElementConstants.ts
plugins/ui/src/js/src/widget/WidgetUtils.tsx

Closes #649 
**Additional Info:**
- Did not include `validate` prop based off this comment on Text Field PR: https://github.com/deephaven/deephaven-plugins/pull/357#discussion_r1523474450
Some of the snippets I had tested with:
```
def test_on_change(new_value):
print(f"Text changed to {new_value}")
t1 = ui.text_area()
t2 = ui.text_area(on_change=test_on_change)
t3 = ui.text_area(label="Test Label", label_position='side', flex_grow=1.0, flex_shrink=0.75)
t4 = ui.text_area(label="Test Label 2", is_required=True)
t5 = ui.text_area(is_disabled=True, is_hidden=False)
t6 = ui.text_area(is_hidden=True)
t7 = ui.text_area(auto_focus=True)
```

feat: ui.text_area

---

plugins/ui/docs/README.md

- We converted the column names, but `"value"` is still used to reference the value in the dictionary
- Also handle_row_double_press only takes one parameter now

docs: Fix casing in the ui.table examples

---

plugins/plotly-express/src/deephaven/plot/express/plots/PartitionManager.py
plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
plugins/plotly-express/test/deephaven/plot/express/plots/test_distribution.py

Fixes #451 
This was already mostly supported, just needed to remove the exception and fix a small error.
Here is an example
```
iris = dx.data.iris()
violin_x = dx.violin(iris, x="PetalLength", y="Species")
```

fix: Can't pass both x and y to violin, box and strip

---

.github/workflows/build-main-docs.yml
.github/workflows/make-docs.yml
.github/workflows/modified-plugin.yml
plugins/plotly-express/make_docs.py
plugins/ui/make_docs.py
plugins/ui/src/deephaven/ui/components/text_area.py
sphinx_ext/make_docs_utilities.py
tools/plugin_builder.py

1. Plumbs through error codes so `make_docs.py` fails correctly
2. `make_docs.yml` now runs on pull request to main (without sync) so broken docs have to be cleaned up before merge
3. Fixed `text_area.py` so docs are able to build
Tested on my fork

fix: Prevent pushing broken docs to main

---

plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
plugins/ui/test/deephaven/ui/test_hooks.py

Removes `replay_lock` due to  https://github.com/deephaven/deephaven-core/pull/5672

fix: Remove `replay_lock` in `use_table_listener`

---

plugins/ui/docs/components/checkbox.md
plugins/ui/src/deephaven/ui/components/checkbox.py

docs: ui.checkbox

---

plugins/plotly-express/conf.py
plugins/plotly-express/test/__init__.py
plugins/plotly-express/test/deephaven/plot/express/BaseTest.py
plugins/ui/conf.py
templates/widget/{{ cookiecutter.python_project_name }}/test/__init__.py
templates/widget/{{ cookiecutter.python_project_name }}/test/{{ cookiecutter.python_project_name }}/BaseTest.py
templates/widget/{{ cookiecutter.python_project_name }}/test/{{ cookiecutter.python_project_name }}/test.py

Fixes #759 
Startup is not needed, only an instance, so removed the startup.

fix: Remove server startup from python tests

---

plugins/ui/docs/sidebar.json

- We added a whole bunch of docs for components, but they are not visible in the sidebar
- Add them to the sidebar in alphabetical order. Perhaps we'll want groupings at some point

docs: Add missing components to sidebar

---

plugins/ui/docs/Plotting.md
plugins/ui/docs/components/view.md

Having an open div without a closing tag is Invalid markdown. We don't do any validation yet, but was preventing the page from rendering.
Also updated some dh.ui -> deephaven.ui wordings.

docs: fix unclosed html tag in markdown

---

plugins/ui/src/deephaven/ui/components/form.py

- Fixes #694
- Tested with the following:
```python
@ui.component
def ui_form_validation_test():
value, set_value = ui.use_state('')
validation_errors = {"identifier": "Invalid identifier"} if not value.isidentifier() else None
return ui.form(
ui.text_field(value=value, name="identifier", label="Enter identifier", on_change=set_value),
validation_errors=validation_errors,
)
form_validation_test = ui_form_validation_test()
```

feat: Allow validation_errors to be passed into ui.form

---

.gitignore
.pre-commit-config.yaml
README.md
tools/plugin_builder.py

Fixes #632 
Adds a `--watch` mode to `plugin_builder.py`
This goes beyond just editable installs with the goal of automatically running any command that is reasonable to rerun (not config, for example). So this can also be used to rebuild `--docs` automatically, and could rerun tests once I add those in, etc. 
Some of the rerun detection is crude in that "any" file anywhere in the plugins repo will trigger a rerun, but since this is a development script I don't see that as a blocker. It's reasonable that we would run the script in a way that hones in on only building what we want.
Some examples are in the readme

feat: Add watch mode to `plugin_builder.py`

---

plugins/ui/src/deephaven/ui/components/form.py
plugins/ui/src/deephaven/ui/components/picker.py

- Fixes #717 
- Rename `label_alignment` to `label_align` for `form` and `picker`

refactor: rename label_alignment to label_align

---

plugins/ui/src/js/src/elements/TextArea.tsx
plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
plugins/ui/src/js/src/elements/hooks/useFocusEventCallback.ts
plugins/ui/src/js/src/elements/hooks/useKeyboardEventCallback.ts
plugins/ui/src/js/src/elements/hooks/usePressEventCallback.ts
plugins/ui/src/js/src/elements/hooks/useTextAreaProps.ts
plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts

- Fixes #790 
- Switch to `useKeyboardEventCallback` for `text_area` keyboard events
- Add new serialized props for input elements, which contains `defaultValue`, `value`, and `onChange`

fix: text_area on_key_down throws errors

---

plugins/ui/docs/components/slider.md
plugins/ui/docs/components/switch.md
plugins/ui/src/deephaven/ui/components/switch.py

docs: ui.switch

---

templates/widget/{{ cookiecutter.python_project_name }}/plugin_builder.py
tools/plugin_builder.py

Regex strings should generally be raw as in "normal" strings, "\" signifies an escape.

fix: Make regex strings raw

---

.github/workflows/build-main-docs.yml
.github/workflows/make-docs.yml

Fixes #806 
I've tested on my fork and it appears that all files are getting set to the proper mime type

fix: Set mime type correctly on google cloud md files

---

plugins/ui/docs/components/text_field.md
plugins/ui/src/deephaven/ui/components/text_field.py

docs: ui.text_field

---

plugins/ui/src/deephaven/ui/components/combo_box.py
plugins/ui/src/deephaven/ui/components/form.py
plugins/ui/src/deephaven/ui/components/number_field.py
plugins/ui/src/deephaven/ui/components/picker.py
plugins/ui/src/deephaven/ui/components/radio_group.py
plugins/ui/src/deephaven/ui/components/text_area.py
plugins/ui/src/deephaven/ui/components/text_field.py
plugins/ui/src/deephaven/ui/components/types/layout.py

- Fixes #801 
- Set all `label_align` props to default to None
- Deleted `Align` type - duplicate of `Alignment`

fix: set label_align default to None

---

plugins/ui/src/js/src/widget/WidgetUtils.tsx

- Adds #733 
- If the `contextualHelp` prop is a primitive, wrap it in `ContextualHelp` and `Content`

feat: wrap contextual help if primitive

---

.pre-commit-config.yaml

Looks like pre-commit uses its own venv if you specify dependencies, so this version needs to be explicit. Otherwise our local pre-commit hooks will have old dependencies and fail locally

ci: Specify deephaven-plugin-utilities version for pre-commit

---

plugins/ui/src/js/src/layout/ReactPanel.tsx

- Fixes #318 
- Store the previous title to check if an update is needed

fix: dynamically update panel title

---

plugins/ui/src/js/src/elements/TextArea.tsx
plugins/ui/src/js/src/elements/TextField.tsx
plugins/ui/src/js/src/elements/hooks/useTextInputProps.ts
plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts

- Fixes #893 
- Generalize the text area hook to be used for any text input, and make `text_field` use that

fix: text_field events throw error

---

plugins/ui/src/deephaven/ui/components/button_group.py
plugins/ui/src/deephaven/ui/components/types/layout.py

- Fixes #909 
- Rename `alignment` prop to `align` to match [Spectrum](https://react-spectrum.adobe.com/react-spectrum/ButtonGroup.html)

fix: button group align

---

sphinx_ext/deephaven_autodoc.py
sphinx_ext/make_docs_utilities.py

No longer removes newlines, residual from before we were using a table and they were messing with the formatting I believe

fix: Don't strip new lines in dhautofunction

---

sphinx_ext/deephaven_autodoc.py

Goes back to stripping newlines for type descriptions specifically (changed in #805) as those don't parse properly now

fix: Newlines within type description not parsed correctly in docs

---

plugins/ui/src/deephaven/ui/components/combo_box.py
plugins/ui/src/deephaven/ui/components/form.py
plugins/ui/src/deephaven/ui/components/number_field.py
plugins/ui/src/deephaven/ui/components/picker.py
plugins/ui/src/deephaven/ui/components/radio_group.py
plugins/ui/src/deephaven/ui/components/text_area.py
plugins/ui/src/deephaven/ui/components/text_field.py

- Fixes #924 
- Set default of `necessity_indicator` to `None` so the prop can inherit from parents if necessary

fix: set necessity_indicator default to None

---

plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts

- Fixes #948 
- Since `defaultValue` is passed to `useDebouncedOnChange` as `propValue`, `onChange` should be returned so the value can be edited

fix: text input default value

---

plugins/ui/src/js/src/elements/RangeSlider.tsx
plugins/ui/src/js/src/elements/Slider.tsx
plugins/ui/src/js/src/elements/TextArea.tsx
plugins/ui/src/js/src/elements/TextField.tsx
plugins/ui/src/js/src/elements/hooks/useTextInputProps.ts
plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts

- Fixes #754 
- Change slider to use `useDebouncedOnChange`

fix: slider input default value

---

sphinx_ext/deephaven_autodoc.py

Autodoc output was not as expected
Additionally, description was still in the ParamTable object, but can have newlines, so rendering broke.
Snippet of part of button:

fix: Incorrect output in autodoc

---

plugins/plotly-express/docs/README.md
plugins/plotly-express/src/deephaven/plot/express/plots/_private_utils.py
plugins/plotly-express/src/deephaven/plot/express/plots/area.py
plugins/plotly-express/src/deephaven/plot/express/plots/bar.py
plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
plugins/plotly-express/src/deephaven/plot/express/plots/financial.py
plugins/plotly-express/src/deephaven/plot/express/plots/heatmap.py
plugins/plotly-express/src/deephaven/plot/express/plots/hierarchial.py
plugins/plotly-express/src/deephaven/plot/express/plots/line.py
plugins/plotly-express/src/deephaven/plot/express/plots/maps.py
plugins/plotly-express/src/deephaven/plot/express/plots/pie.py
plugins/plotly-express/src/deephaven/plot/express/plots/scatter.py
plugins/plotly-express/src/deephaven/plot/express/types/__init__.py
plugins/plotly-express/src/deephaven/plot/express/types/plots.py
plugins/plotly-express/test/deephaven/plot/express/BaseTest.py
plugins/plotly-express/test/deephaven/plot/express/plots/test_area.py

Fixes #8 
Allows passing in a pandas dataframe to all plots that take a table.
Example:
```import plotly.express as px
df = px.data.iris()
fig = dx.scatter(df, x="sepal_width", y="sepal_length", color="species", symbol="species")
```
Also now require a table (or similar) passed in for all plot types, as is already done for `density_heatmap`. This was part of #1, although not the full changes needed, but made sense to do now. This doesn't break anything as the plot isn't expected to work without a table anyways.
Additionally adds a test utility for chart comparisons. Not so essential that all tests need to change per se but reduces future  test boilerplate.

feat: Allow passing in a pandas dataframe to dx plots

---

plugins/ui/src/deephaven/ui/_internal/__init__.py
plugins/ui/src/deephaven/ui/_internal/utils.py
plugins/ui/src/deephaven/ui/elements/BaseElement.py
plugins/ui/src/deephaven/ui/elements/UITable.py
plugins/ui/test/deephaven/ui/test_utils.py

The `dict_to_camel_case` function was doing a bit too much based on its name. This separates the utils a bit so they are better named and `dict_to_camel_case` is true camel case without our special keys and removing Nones.

refactor: Separate remove_empty_keys and dict_to_camel_case behavior

---

plugins/ui/src/deephaven/ui/_internal/utils.py
plugins/ui/test/deephaven/ui/test_utils.py

Changed a prop to `if_` and noticed the `to_camel_case` method throws with index out of bounds because it ends up trying to access characters of an empty string. Figured we should preserve leading and trailing underscores, but convert anything in the middle to camelCase.

fix: to_camel_case fails on leading or trailing underscores

---

.github/workflows/build-python-package.yml
.github/workflows/make-docs.yml
.github/workflows/modified-plugin.yml
.github/workflows/pre-commit.yml
.github/workflows/release-python-package.yml
.github/workflows/test-js-packages.yml
.github/workflows/test-python-package.yml

Fixes #969 - Switches to use the `salmon-sync` action for docs uploads 
Fixes #970 - Cleans up warnings. For the most part this was just version bumps. The most significant change was in caching for `test-js-packages.yml`. I followed [these](https://github.com/actions/cache/blob/main/save/README.md#always-save-cache) directions to migrate that.
Tested on my fork

ci: Switch to salmon-sync action and fix action warnings

---

plugins/ui/docs/components/action_group.md
plugins/ui/docs/components/action_menu.md
plugins/ui/docs/sidebar.json
plugins/ui/src/deephaven/ui/components/action_menu.py

docs: ui.action_menu

---

.github/workflows/test-python-package.yml
README.md
plugins/plotly-express/tox.ini
plugins/ui/tox.ini

fixes #965 
Default to test with 3.8
Also adds other environments to run. A tiny bit more maintenance when we add/remove version support but useful for both the gh action and easily running different versions locally

test: default tox to 3.8

---

plugins/ui/src/js/src/elements/Dialog.tsx
plugins/ui/src/js/src/elements/hooks/useConditionalCallback.test.ts
plugins/ui/src/js/src/elements/hooks/useConditionalCallback.ts
plugins/ui/src/js/src/elements/hooks/useFocusEventCallback.ts
plugins/ui/src/js/src/elements/hooks/useFormEventCallback.ts
plugins/ui/src/js/src/elements/hooks/useKeyboardEventCallback.ts
plugins/ui/src/js/src/elements/hooks/usePressEventCallback.ts

- Takes a condition that if it is false, will return undefined instead of the callback
- Useful for the pattern where we're wrapping a callback but don't want to pass a callback to a child if we didn't receive a callback

feat: Add useConditionalCallback hook

---

plugins/ui/docs/hooks/README.md
plugins/ui/docs/hooks/overview.md
plugins/ui/docs/hooks/use_callback.md
plugins/ui/docs/hooks/use_cell_data.md
plugins/ui/docs/hooks/use_column_data.md
plugins/ui/docs/hooks/use_ref.md
plugins/ui/docs/hooks/use_table_data.md
plugins/ui/docs/sidebar.json

- Added a Hooks overview page detailing some of the rules about hooks, and linking to some of the hooks
- Also add the `use_callback` docs page
- Closes #808, closes #996, closes #809, closes #1014, closes #1015, closes #1016

docs: Add docs for use_callback, use_ref, hooks overview page

---

plugins/ui/docs/components/avatar.md
plugins/ui/docs/sidebar.json
plugins/ui/src/deephaven/ui/components/__init__.py
plugins/ui/src/deephaven/ui/components/avatar.py
plugins/ui/src/deephaven/ui/types/types.py
plugins/ui/src/js/src/elements/model/ElementConstants.ts
plugins/ui/src/js/src/widget/WidgetUtils.tsx

feat: ui.avatar

---

plugins/plotly-express/src/deephaven/plot/express/plots/line.py
plugins/plotly-express/test/deephaven/plot/express/plots/test_line.py
tests/app.d/ui_flex.py

Fixes #991 
Used code from that issue
```
from deephaven.plot import express as dx
from deephaven.plot.figure import Figure
_stocks = dx.data.stocks()
p = dx.line(_stocks, "Timestamp", "Random")
```

fix: switch to webgl by default for line plot

---

plugins/plotly-express/docs/indicator.md
plugins/plotly-express/src/deephaven/plot/express/plots/indicator.py
plugins/plotly-express/src/deephaven/plot/express/types/__init__.py
plugins/plotly-express/src/deephaven/plot/express/types/plots.py

spec for #1019 
I haven't really written a spec for `dx` before but it made sense to me to just put it in a new function with `NotImplementedError`.
Instead of just enabling one indicator, you can create multiple at one time with a plot by that makes subplots of indicators. This enables, for example, the creation of a new indicator automatically as a new symbol ticks in.  
The default behavior is only a `number` if you only provide `value` and `number+delta` if you provide `reference` as well.
https://plotly.com/python/indicator/
Syntax is otherwise generally in line with other `dx` functions and most other behavior is fairly straightforward.

feat: `dx.indicator` spec

---

plugins/ui/src/deephaven/ui/components/combo_box.py
plugins/ui/src/deephaven/ui/components/date_field.py
plugins/ui/src/deephaven/ui/components/date_picker.py
plugins/ui/src/deephaven/ui/components/date_range_picker.py
plugins/ui/src/deephaven/ui/components/picker.py
plugins/ui/src/deephaven/ui/components/progress_bar.py
plugins/ui/src/deephaven/ui/components/time_field.py
plugins/ui/src/deephaven/ui/elements/Element.py
plugins/ui/src/deephaven/ui/elements/__init__.py

- Fixes #988 
- Adds `NodeType`, which mirrors the React Node type

fix: label prop typing

---

plugins/ui/src/deephaven/ui/components/action_menu.py
plugins/ui/src/deephaven/ui/components/column.py
sphinx_ext/deephaven_autodoc.py

Fixes https://deephaven.atlassian.net/browse/DH-18247
Allows autodoc functions to have no parameters and adds better error checking for params to ensure that all expected parameters are there in a fine-tuned way.
Tested on all existing docs as well as a local `use_render_queue` doc.

fix: Allow autodoc functions to have no parameters

---

plugins/ui/docs/sidebar.json

Forgot to add `menu` and `menu_trigger` to the side bar.
https://deephaven.atlassian.net/browse/DH-18089

fix: add menu and menu_trigger to sidebar

---

cog.toml
lerna.json
package.json

- Allow release branches to bump versions - we need this for hotfix branches, and already have it on the ui-v0.15 branch: 2803feae22dce73a6fe38fdb85a8a07b4f35cc79
- Need to update template to the correct format. Already did this on the `release/ui-v0.15` branch: #570 
- Take note there are still some issues to beware of when bumping a release branch: https://github.com/deephaven/deephaven-plugins/issues/557

build: Update the changelogPreset to use conventionalcommits, allow release branches to bump versions

---

plugins/plotly-express/docs/sidebar.json

file was renamed, but not updated in sidebar. In future the sidebar vailidator would have caught this.
Also renamed it to drop the command from the title, just the concept to match the style of the other names.

docs: fix renamed unsafe-figure-update

---

plugins/ui/src/js/src/layout/ReactPanel.tsx
plugins/ui/src/js/src/layout/ReactPanelErrorBoundary.test.tsx
plugins/ui/src/js/src/layout/ReactPanelErrorBoundary.tsx

- ReactPanelErrorBoundary would throw an error if children was undefined
- Just render `null` if `children` is `undefined`
- Tested using the steps in DH-18461. Unable to figure out steps to reproduce in just DHC.
- There may still be a fix higher up in Enterprise, but this at least ensures ReactPanelErrorBoundary is more robust and we don't totally euchre our layout

fix: Ensure ReactPanelErrorBoundary handles undefined children

---

plugins/ui/src/js/src/layout/ReactPanel.tsx
plugins/ui/src/js/src/layout/ReactPanelErrorBoundary.test.tsx
plugins/ui/src/js/src/layout/ReactPanelErrorBoundary.tsx

- ReactPanelErrorBoundary would throw an error if children was undefined
- Just render `null` if `children` is `undefined`
- Tested using the steps in DH-18461. Unable to figure out steps to reproduce in just DHC.
- There may still be a fix higher up in Enterprise, but this at least ensures ReactPanelErrorBoundary is more robust and we don't totally euchre our layout

fix: Ensure ReactPanelErrorBoundary handles undefined children (#1089)

---

plugins/ui/docs/add-interactivity/respond-to-events.md
plugins/ui/docs/sidebar.json

https://deephaven.atlassian.net/browse/DOC-346

docs: respond to events

---

plugins/ui/docs/describing/ui_with_tables.md
plugins/ui/docs/describing/work_with_tables.md
plugins/ui/docs/sidebar.json

https://deephaven.atlassian.net/browse/DOC-374
Update this section to improve content. Renamed to "UI with Tables" to avoid naming conflict with other documentation.

docs: update work with tables

---

plugins/plotly-express/conf.py
plugins/ui/conf.py
plugins/ui/docs/hooks/use_row_list.md

Fixes https://deephaven.atlassian.net/browse/DOC-355 by "making all links external", meaning they are passthrough instead of being processed by myst parser. In particular the absolute paths were considered invalid because they were file locations that didn't exist at build time.

fix: Make docs links passthrough

---

plugins/plotly-express/setup.cfg

Plotly's version was not pinned, and there are breaking changes in 6.0.0, so tests were failing

fix: Pin plotly version

---

plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
plugins/ui/src/js/src/widget/WidgetHandler.tsx
plugins/ui/src/js/src/widget/WidgetUtils.test.tsx
plugins/ui/src/js/src/widget/WidgetUtils.tsx

- Client was calling a closeCallable function each time any callable was no longer rendered
- Callables as part of the regular render cycle that didn't change were being recreated every time
- Since it wasn't the same object between renders, closeCallable was getting called for a previous instance of that callable but with the same ID
- Server side was unnecessarily listening for those to close callables as part of the regular render cycle
- Things that are no longer rendered are already cleaned up by the server, don't need to/shouldn't listen to the client for when to clean those up. Only needed for the temporary callables
- Tested by using the snippet from DH-18536:
```python
from deephaven import ui, time_table
@ui.component
def ui_resetable_table():
table, set_table = …
```

fix: Callable cleanup race (DH-18536)

---

.github/workflows/modified-plugin.yml

I dropped the `s` in `heads` when modifying this action last week preventing the docs publishing when pushed to main

ci: Fix ref for main docs push publishing

---

.github/workflows/publish-prod-docs.yml
.github/workflows/publish-staging-docs.yml

Just made a copy of the publish-docs action for prod that is filtered on main/release branches and checks for push. Then the preview action which just checks it's triggered by a pull request.

ci: Make separate staging action

---

.github/workflows/publish-docs.yml

Changes from  `/core/<plugin>/docs/<version>` to `/core/<plugin>/<version>/docs`

ci: Fix docs preview link

---

plugins/plotly-express/conf.py
plugins/ui/conf.py
sphinx_ext/deephaven_markdown_translator.py

This is a bit of a hack, but works. Checked the output of UI docs in `components` and ensured they kept the `../` in their image paths.

build: Add custom sphinx translator to fix relative image paths in output

---

plugins/ui/docs/components/labeled_value.md
plugins/ui/src/deephaven/ui/components/labeled_value.py
plugins/ui/src/deephaven/ui/components/types/Intl/list_format.py
plugins/ui/src/deephaven/ui/components/types/__init__.py

- Implements [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat) for use in ui.labeled_value. Currently it is only supported in [LabeledValue](https://react-spectrum.adobe.com/react-spectrum/LabeledValue.html), but it could be used in components that might support it in the future.
Test Snippet
```python
@ui.component
def labeled_value_list_formatting():
return [
ui.labeled_value(
label="Interests",
value=["Travel", "Hiking", "Snorkeling", "Camping"],
format_options={"type": "conjunction"},
),
ui.labeled_value(
label="Travel Destination",
value=["Paris", "Tokyo", "New York", "Sydney"],
format_options={"type": "disjunction"},
),
ui.labeled_value(
label="Clothing Sizes",
value=["XS", "S", …
```

feat: List format options for ui.labeled_value

---

plugins/ui/src/js/src/widget/WidgetHandler.tsx

- Issue caused by #1113
- Re-opening the widget would call an old version of the callback
- Reset the rendered callable map when re-initializing the widget
- Tested with component, ran snippet, pressed button, then re-ran snippet and pressed button. It continued to print text:
```
b = ui.button("Print something", on_press=print)
```

fix: Re-opening widget would break interactivity (DH-18090)

---

package-lock.json
plugins/plotly-express/src/js/package.json
plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts

Probably need to make this more robust, but this gets the type check to pass.
Looks like `@deephaven/chart` depends on `^1.0.0-0.37.6` or something like that while plotly-express was depending on a pinned version of the jsapi-types causing some conflict.

fix: Fix type version for plotly-express

---

plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
plugins/ui/src/js/src/widget/WidgetHandler.tsx

- We were throwing if the jsonClient was null, which is something that can't happen in Core, but is possible in Enterprise (due to a query restarting).
- Added unit tests to test
- Tested against dev-sanluis using the steps from DH-18461

fix: Handle a null jsonClient correctly (DH-18461)

---

plugins/ag-grid/src/js/src/AgGridWidget.tsx

Fixed type that was failing https://github.com/deephaven/deephaven-plugins/actions/runs/14093526373/job/39475806319?pr=1126

fix: incorrect table type in ag grid plugin

---

.github/workflows/build-python-package.yml
.github/workflows/conventional-pr-check.yml
.github/workflows/e2e.yml
.github/workflows/modified-plugin.yml
.github/workflows/publish-alpha.yml
.github/workflows/publish-packages.yml
.github/workflows/release-python-package.yml
.github/workflows/request-docs-review.yml
.github/workflows/test-js-packages.yml
.github/workflows/test-python-package.yml

- We were still using Ubuntu 22, which uses Java 11 by default
- deephaven-server released 0.39.0, which now requires Java 17 for Jetty 12 support: https://github.com/deephaven/deephaven-core/pull/6037
- Just update to Ubuntu 24, may as well do this anyway. Uses Java 17 by default

ci: Update images to Ubuntu 24

---

tools/validate.sh

- We were doing a `gh release list --limit 1` command to verify the user's permissions
- If the user had `less` configured as their GH CLI pager, then it would require user input to proceed
- https://github.com/cli/cli/issues/3617

chore: Allow release to proceed without requiring user input

---

plugins/plotly-express/docs/area.md
plugins/plotly-express/docs/bar.md
plugins/plotly-express/docs/box.md
plugins/plotly-express/docs/candlestick.md
plugins/plotly-express/docs/density_heatmap.md
plugins/plotly-express/docs/funnel-area.md
plugins/plotly-express/docs/funnel.md
plugins/plotly-express/docs/histogram.md
plugins/plotly-express/docs/icicle.md
plugins/plotly-express/docs/indicator.md
plugins/plotly-express/docs/line-3d.md
plugins/plotly-express/docs/line-polar.md
plugins/plotly-express/docs/line-ternary.md
plugins/plotly-express/docs/line.md
plugins/plotly-express/docs/ohlc.md
plugins/plotly-express/docs/pie.md
plugins/plotly-express/docs/scatter-3d.md
plugins/plotly-express/docs/scatter-polar.md
plugins/plotly-express/docs/scatter-ternary.md
plugins/plotly-express/docs/scatter.md
plugins/plotly-express/docs/strip.md
plugins/plotly-express/docs/sunburst.md
plugins/plotly-express/docs/treemap.md
plugins/plotly-express/docs/violin.md

DOC-754: modifies the Sphinx configuration specifically when building plotly-express docs to silence `myst.header` warnings that occur when there are non-consecutive heading levels. (This seems to be intentional in some docs where heading levels are skipped for layout reasons)
If you wish to suppress specific warnings for plotly-express build logs, add the warning to the `suppress_warnings` configuration option in the `conf.py` file.

docs: DOC-754: silence non-consecutive header warning

---

plugins/plotly-express/docs/limitations.md
plugins/plotly-express/docs/sidebar.json

Added general limitations page, with webgl on chrome to start.

docs: DOC-684: add webgl chrome limitations

---

plugins/ui/docs/components/dialog.md
plugins/ui/docs/components/dialog_trigger.md
plugins/ui/docs/components/html.md
plugins/ui/src/deephaven/ui/components/combo_box.py
plugins/ui/src/deephaven/ui/components/dialog_trigger.py
plugins/ui/src/deephaven/ui/components/list_view.py
plugins/ui/src/deephaven/ui/components/picker.py

Fixes Doc-759.
Resolves indentation and block quote formatting issues in the UI docs. Also, removes references to `selection` and `thread` in the API reference to prevent build warnings as modules are not defined.

docs: DOC-759: warnings when building deephaven UI docs

---

plugins/plotly-express/docs/sub-plots.md
plugins/plotly-express/src/deephaven/plot/express/plots/_layer.py
plugins/plotly-express/src/deephaven/plot/express/plots/subplots.py
plugins/plotly-express/test/deephaven/plot/express/plots/test_make_subplots.py

Originally failing was the following:
```
tips = dx.data.tips() # import a ticking version of the Tips dataset
tipping_plots = dx.make_subplots(
dx.scatter(tips, x="TotalBill", y="Tip", by="Sex",
title="Tip amount by total bill"),
dx.scatter(tips, x="TotalBill", y="Tip", by="Sex",
title="Tip amount by total bill"),
rows=2, cols=1, shared_xaxes=True, shared_yaxes=False
)
```
Added docs for shared axes as well

fix: DH-19036: Fix failing subplot creation

---

plugins/ag-grid/src/js/package.json
plugins/ag-grid/src/js/src/AgGridView.tsx
plugins/ag-grid/src/js/src/datasources/DeephavenViewportDatasource.ts
plugins/ag-grid/src/js/src/datasources/index.ts
plugins/ag-grid/src/js/src/index.ts
plugins/ag-grid/src/js/src/renderers/index.ts
plugins/ag-grid/src/js/src/utils/index.ts
plugins/ag-grid/src/js/src/vite-env.d.ts
plugins/ag-grid/src/js/tsconfig.json
plugins/ag-grid/src/js/vite.config.ts
plugins/manifest.json

- Wire it up similar to the plotly-express plugin, such that it can be imported as a module or installed as a plugin
- Export everything from an index.ts so imports can all be done from the root of the package
- Verified the plugin still worked, and that all the files were output correctly to the `dist` build folder

build: Bundle AG Grid plugin so it can be imported in other projects

---

plugins/ag-grid/src/js/src/AgGridView.tsx
plugins/ag-grid/src/js/src/AgGridWidget.tsx
plugins/ag-grid/src/js/src/datasources/DeephavenViewportDatasource.ts

For DH-19685. Implements column and row auto-sizing for AG Grid tables. When the grid is initialized and data is loaded in, columns are auto-sized to fit their largest cell content, while row heights are set based on theme parameters

fix: DH-19685: Auto-size AG Grid to fit cell content

---

package-lock.json
plugins/ag-grid/src/js/package.json

- Allows for our tools to be used in these packages without overrides

build(ag-grid): Allow peer dependency of React to be 17, 18, or 19

---

plugins/simple-pivot/src/js/package.json

- Will allow us to publish versions in the future if necessary
- Was currently causing issues when releasing other plugins, as it would also try and publish simple-pivot and fail, e.g. https://github.com/deephaven/deephaven-plugins/actions/runs/16222307802/job/45805843680
> Found 1 package to publish:
> - @deephaven/js-plugin-simple-pivot => 0.0.3-dev.2
> lerna info auto-confirmed 
> lerna info publish Publishing packages to npm...
> lerna ERR! E422 Error verifying sigstore provenance bundle: Failed to validate repos

build: Add provenance info to simple-pivot plugin

---

plugins/ui/docs/tutorial.md

https://deephaven.atlassian.net/browse/DOC-843

fix: DOC-843: Update tutorial

---

plugins/plotly-express/conf.py
plugins/ui/conf.py
sphinx_ext/deephaven_code_block.py

Previously was only preserving `python` as the language, not `py` or `groovy` (we don't have any groovy in these docs right now)
Also modifies the myst global config value from the plugin setup to augment it instead of setting in each `conf.py`. It's an empty set by default.

build: Fix docs code fence plugin not registering py or groovy

---

plugins/ui/src/js/src/widget/WidgetHandler.tsx

DH-19988 for Grizzly
Same test plan as before, but you don't need `start-community` and should be running `rc/grizzly` for the DHE UI. Make sure to `npm install` both plugins and DHE. The PQ is already on `dev-grizzly2` and the dashboard it creates is `dh_19988`

fix: DH-19988: Render error superceding document error on reinitialize (#1222)

---

.github/workflows/pre-commit.yml
.github/workflows/test-python-package.yml
README.md
plugins/ag-grid/tox.ini
plugins/matplotlib/tox.ini
plugins/packaging/tox.ini
plugins/pivot/tox.ini
plugins/plotly-express/tox.ini
plugins/simple-pivot/tox.ini
plugins/theme-pack/tox.ini
plugins/ui/test/deephaven/ui/test_ui_table.py
plugins/ui/tox.ini
plugins/utilities/tox.ini
templates/widget/{{ cookiecutter.python_project_name }}/tox.ini

- Python 3.8 is past EOL: https://devguide.python.org/versions/
- jpy no longer publishes wheels for Python 3.8: https://github.com/jpy-consortium/jpy/pull/201
- Logged a ticket for deephaven-core to update requirements: https://deephaven.atlassian.net/browse/DH-20615
- For the deephaven-plugins tests, just remove 3.8 and add 3.13 (since it should be supported as well)

ci: Remove python 3.8 from tests and add python 3.13
